package vterds;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Administrator_MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Administrator_MainMenu
     */
    public Administrator_MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        functionPage_AD = new javax.swing.JTextArea();
        editUsers_AD = new javax.swing.JButton();
        advanceElectionStatus_AD = new javax.swing.JButton();
        lastLoginDisplay_AD = new javax.swing.JLabel();
        addUsers_AD = new javax.swing.JButton();
        nameDisplay_AD = new javax.swing.JLabel();
        userTypeDisplay_AD = new javax.swing.JLabel();
        dateAndTimeDisplay_AD = new javax.swing.JLabel();
        statusDisplay_AD = new javax.swing.JLabel();
        logout_AD = new javax.swing.JButton();
        locationDisplay_AD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        functionPage_AD.setColumns(20);
        functionPage_AD.setRows(5);
        jScrollPane1.setViewportView(functionPage_AD);

        editUsers_AD.setText("Edit User");
        editUsers_AD.setToolTipText("Edit User botton");

        advanceElectionStatus_AD.setText("Advance Election Status");
        advanceElectionStatus_AD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanceElectionStatus_ADActionPerformed(evt);
            }
        });

        lastLoginDisplay_AD.setText("Last Login:");
        lastLoginDisplay_AD.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addUsers_AD.setText("Add Users");
        addUsers_AD.setToolTipText("Add User button");
        addUsers_AD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsers_ADActionPerformed(evt);
            }
        });

        nameDisplay_AD.setText("John Smith");
        nameDisplay_AD.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        userTypeDisplay_AD.setText("Adminstrator");
        userTypeDisplay_AD.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dateAndTimeDisplay_AD.setText("Date and Time");
        dateAndTimeDisplay_AD.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        statusDisplay_AD.setText("Status:");
        statusDisplay_AD.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logout_AD.setText("Logout");
        logout_AD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_ADActionPerformed(evt);
            }
        });

        locationDisplay_AD.setText("Location:");
        locationDisplay_AD.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastLoginDisplay_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateAndTimeDisplay_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addUsers_AD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editUsers_AD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(advanceElectionStatus_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDisplay_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userTypeDisplay_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(statusDisplay_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationDisplay_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout_AD)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(statusDisplay_AD, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addComponent(locationDisplay_AD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(logout_AD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(nameDisplay_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userTypeDisplay_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateAndTimeDisplay_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastLoginDisplay_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(addUsers_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editUsers_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(advanceElectionStatus_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void advanceElectionStatus_ADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanceElectionStatus_ADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advanceElectionStatus_ADActionPerformed

    private void logout_ADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_ADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_ADActionPerformed

    private void addUsers_ADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsers_ADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUsers_ADActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Administrator_MainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUsers_AD;
    private javax.swing.JButton advanceElectionStatus_AD;
    private javax.swing.JLabel dateAndTimeDisplay_AD;
    private javax.swing.JButton editUsers_AD;
    private javax.swing.JTextArea functionPage_AD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastLoginDisplay_AD;
    private javax.swing.JLabel locationDisplay_AD;
    private javax.swing.JButton logout_AD;
    private javax.swing.JLabel nameDisplay_AD;
    private javax.swing.JLabel statusDisplay_AD;
    private javax.swing.JLabel userTypeDisplay_AD;
    // End of variables declaration//GEN-END:variables
}
