package vterds;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class firstSecond_ReturningOfficier_MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form firstSecond_ReturningOfficier_MainMenu
     */
    public firstSecond_ReturningOfficier_MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameDisplay_RO = new javax.swing.JLabel();
        userTypeDisplay_RO = new javax.swing.JLabel();
        lastLoginDisplay_RO = new javax.swing.JLabel();
        tabulateButton_RO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        functionPage_RO = new javax.swing.JTextArea();
        createBallotListingFileButton_RO = new javax.swing.JButton();
        addTabulatedVotesToRiding_RO = new javax.swing.JButton();
        locationDisplay_RO = new javax.swing.JLabel();
        logout_RO = new javax.swing.JButton();
        statusDisplay_RO = new javax.swing.JLabel();
        dateAndTimeDisplay_RO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameDisplay_RO.setText("John Smith");
        nameDisplay_RO.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        userTypeDisplay_RO.setText("1st / 2nd Returning Off");
        userTypeDisplay_RO.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lastLoginDisplay_RO.setText("Last Login:");
        lastLoginDisplay_RO.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabulateButton_RO.setText("Tabulate/Tabulate Again (2nd RO)");
        tabulateButton_RO.setToolTipText("");
        tabulateButton_RO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabulateButton_ROActionPerformed(evt);
            }
        });

        functionPage_RO.setColumns(20);
        functionPage_RO.setRows(5);
        jScrollPane1.setViewportView(functionPage_RO);

        createBallotListingFileButton_RO.setText("Create Ballot Listing File");
        createBallotListingFileButton_RO.setToolTipText("");

        addTabulatedVotesToRiding_RO.setText("Add Tabulated Votes to Riding");
        addTabulatedVotesToRiding_RO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTabulatedVotesToRiding_ROActionPerformed(evt);
            }
        });

        locationDisplay_RO.setText("Location:");
        locationDisplay_RO.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logout_RO.setText("Logout");
        logout_RO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_ROActionPerformed(evt);
            }
        });

        statusDisplay_RO.setText("Status:");
        statusDisplay_RO.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dateAndTimeDisplay_RO.setText("Date and Time");
        dateAndTimeDisplay_RO.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastLoginDisplay_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateAndTimeDisplay_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tabulateButton_RO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(createBallotListingFileButton_RO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addTabulatedVotesToRiding_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDisplay_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userTypeDisplay_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(statusDisplay_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationDisplay_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout_RO)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(statusDisplay_RO, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addComponent(locationDisplay_RO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(logout_RO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(nameDisplay_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userTypeDisplay_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateAndTimeDisplay_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastLoginDisplay_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(tabulateButton_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(createBallotListingFileButton_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addTabulatedVotesToRiding_RO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabulateButton_ROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabulateButton_ROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabulateButton_ROActionPerformed

    private void addTabulatedVotesToRiding_ROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTabulatedVotesToRiding_ROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTabulatedVotesToRiding_ROActionPerformed

    private void logout_ROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_ROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_ROActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstSecond_ReturningOfficier_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstSecond_ReturningOfficier_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstSecond_ReturningOfficier_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstSecond_ReturningOfficier_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new firstSecond_ReturningOfficier_MainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTabulatedVotesToRiding_RO;
    private javax.swing.JButton createBallotListingFileButton_RO;
    private javax.swing.JLabel dateAndTimeDisplay_RO;
    private javax.swing.JTextArea functionPage_RO;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastLoginDisplay_RO;
    private javax.swing.JLabel locationDisplay_RO;
    private javax.swing.JButton logout_RO;
    private javax.swing.JLabel nameDisplay_RO;
    private javax.swing.JLabel statusDisplay_RO;
    private javax.swing.JButton tabulateButton_RO;
    private javax.swing.JLabel userTypeDisplay_RO;
    // End of variables declaration//GEN-END:variables
}
